export const products=[
  {
      "Name": "3D Panther",
      "product_code": "MS001",
      "description": "A realistic model of a panther ,fabricated with precision to give a captivating look.",
      "dimension (Standard)": "60\"*24\"*18\"",
      "Weight (Kg)": null,
      "color": null,
      "category": "Connoisseur",
      "imageURL": "https://drive.google.com/thumbnail?id=1a-tq5-Oor2mXiVmCc1vwYlGe_QcFd-fU",
      "pic_2": "https://drive.google.com/file/d/1OKYDcqxqiYwTreSOql0p57kPpv9846iE/view",
      "pic_3 link": "MS001_pic3.jpeg - Google Drive",
      "pic_4 link": null
    },
     {
      "Name": "Flying Birds",
      "product_code": "MS002",
      "description": "A carving on metallic sheet revealing natural instinct of birds-Flight.Birds teach a great life lesson.",
      "dimension (Standard)": "-- *96\"*48\"",
      "Weight (Kg)": null,
      "color": null,
      "category": "Luxury",
      "imageURL": "MS002.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Metal Ball",
      "product_code": "MS003",
      "description": "A striking metallic ball for enhancing outdoor area .Metallic rings amalgmate to manifest artistry.Colour can be customised as per requirement.",
      "dimension (Standard)": "6.5' Diameter",
      "Weight (Kg)": null,
      "color": null,
      "category": "Luxury",
      "imageURL": "MS003.jpg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
  
    {
      "Name": "Metal Ball",
      "product_code": "MS004",
      "description": "An enormous metallic ball to magnify splendour of garden . Intricate floral design generates winsomeness.",
      "dimension (Standard)": "6' Diameter",
      "Weight (Kg)": null,
      "color": null,
      "category": "Luxury",
      "imageURL": "MS004.png - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Metal Flambeau",
      "product_code": "MS005",
      "description": "4 feet high metallic decorative pieces with illumination .Colour combination to be customised as per requirement",
      "dimension (Standard)": "2'",
      "Weight (Kg)": 6,
      "color": null,
      "category": "Regular",
      "imageURL": "MS005.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
    {
      "Name": "Metal Flower Pot on Piller",
      "product_code": "MS006",
      "description": "4 feet high metallic decorative pieces with illumination .Colour combination to be customised as per requirement",
      "dimension (Standard)": "4' * 1'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Regular",
      "imageURL": "MS006.jpg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Long Island Lamp",
      "product_code": "MS007",
      "description": "4 feet high metallic decorative pieces with illumination .Colour combination to be customised as per requirement",
      "dimension (Standard)": "8' (4/6 mm Thickness)",
      "Weight (Kg)": null,
      "color": null,
      "category": "Luxury",
      "imageURL": "MS007.jpg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Floral Pillers (Set of Three)",
      "product_code": "MS008",
      "description": "Intricate floral engraving manifests creativity as well as provide multiple decor ideas. These pillars can be illuminated and customised as per need",
      "dimension (Standard)": "(3' * 1'), (4' * 1'), (6' * 1')",
      "Weight (Kg)": null,
      "color": null,
      "category": "Regular",
      "imageURL": "MS008 pic-01.jpeg - Google Drive",
      "pic_2": "MS008 pic2.jpeg - Google Drive",
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Copper Fountain",
      "product_code": "MS009",
      "description": "An indoor and outdoor fountain emitting soothing effect as well as serving purpose of a natural humidifier",
      "dimension (Standard)": "5'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Luxury",
      "imageURL": "MS009.jpg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Copper Fountain",
      "product_code": "MS010",
      "description": "An indoor and outdoor fountain emitting soothing effect as well as serving purpose of a natural humidifier",
      "dimension (Standard)": "5'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Luxury",
      "imageURL": "MS010.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Copper Fountain",
      "product_code": "MS011",
      "description": "An indoor and outdoor fountain emitting soothing effect as well as serving purpose of a natural humidifier",
      "dimension (Standard)": "5'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Luxury",
      "imageURL": "MS011.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Seeds of Lights",
      "product_code": "MS012",
      "description": "Marvel in sculpturing as well as engineering skills are also involved in creating them .These installations are dynamic compositions in stainless steel ,glass , light and should be termed as a 'gateway to celebration in light'",
      "dimension (Standard)": "24'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS012-pic1.jpeg - Google Drive",
      "pic_2": "MS012-pic2.jpeg - Google Drive",
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Bunch of Buds(40 Buds)",
      "product_code": "MS013",
      "description": "Marvel in sculpturing as well as engineering skills are also involved in creating them .These installations are dynamic compositions in stainless steel ,glass , light and should be termed as a 'gateway to celebration in light'",
      "dimension (Standard)": "3.5'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS013 pic1.jpeg - Google Drive",
      "pic_2": "MS013 pic2.jpeg - Google Drive",
      "pic_3 link": "MS013 pic3.jpeg - Google Drive",
      "pic_4 link": null
    },
     {
      "Name": "Garden Hen (Set of Eight)",
      "product_code": "MS014",
      "description": "These objects of joy can induce state of euphoria if installed in garden area. Metallic effigies of ostrich and hen release positive vibes and elation",
      "dimension (Standard)": "18\" * 18\"",
      "Weight (Kg)": "2/Each",
      "color": null,
      "category": "Connoisseur",
      "imageURL": "MS014.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Pair of Ostrich (Set of Two)",
      "product_code": "MS015",
      "description": "These objects of joy can induce state of euphoria if installed in garden area. Metallic effigies of ostrich and hen release positive vibes and elation",
      "dimension (Standard)": "87\"/77\"",
      "Weight (Kg)": null,
      "color": null,
      "category": "Connoisseur",
      "imageURL": "MS015 pic1.jpg - Google Drive",
      "pic_2": "MS015pic2.png - Google Drive",
      "pic_3 link": "oak40a_ls1_hres_1024x1024 (1).jpg - Google Drive",
      "pic_4 link": null
    },
    {
      "Name": "Wind Spinner",
      "product_code": "MS016",
      "description": "This garden spinner is constructed with durable iron metal components and long lasting combo finish of paint and foil, bright metallic and reflective painting creates a visual sensation in the garden",
      "dimension (Standard)": "9'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Luxury",
      "imageURL": "MS016_pic1.jpeg - Google Drive",
      "pic_2": "IMG_3595.MOV - Google Drive",
      "pic_3 link": "IMG_3590.jpeg - Google Drive",
      "pic_4 link": null
    },
     {
      "Name": "Plant Holder",
      "product_code": "MS017",
      "description": "Metallic structure created out of iron rods stand majestically towering over in garden area. The hanging baskets add elegance and eventually generate soothing ambience",
      "dimension (Standard)": "8'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Luxury",
      "imageURL": "MS017.jpg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "SS Stone",
      "product_code": "MS018",
      "description": "Stainless steel smooth sculpture and engineering marvel suitable for play ground area and decoration",
      "dimension (Standard)": "2' Base, 1' Height, 2mm Thickness",
      "Weight (Kg)": null,
      "color": null,
      "category": "Connoisseur",
      "imageURL": "MS018.jpg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Metal Twirl of Rings",
      "product_code": "MS019",
      "description": "A circular structure 6 feet in  diameter created with metallic rings adds gaudy appeal to indoor and outdoor area",
      "dimension (Standard)": "6.5'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Connoisseur",
      "imageURL": "MS019.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Flowers on Metal",
      "product_code": "MS020",
      "description": "An alluring decorative  floral pattern to capture swanky interiors .The light effect adds to extra impact and and magnify glitzy appeal",
      "dimension (Standard)": "8' * 4' * 1mm",
      "Weight (Kg)": null,
      "color": null,
      "category": "Luxury",
      "imageURL": "MS020.jpg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Horse Shape Pot",
      "product_code": "MS021",
      "description": "Iron framework blended skillfully rendering shape of a horse and an enchanting piece which will draw attention of spectators",
      "dimension (Standard)": "4'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Luxury",
      "imageURL": "MS021.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Pair of Cat",
      "product_code": "MS022",
      "description": "An endearing piece of art ,this pair of cats is delightful as well would be awed by onlookers",
      "dimension (Standard)": "3.5'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Connoisseur",
      "imageURL": "MS022.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Bunch of Butterfly",
      "product_code": "MS023",
      "description": "A towering sculpture of steel radiating diffused lights of enchanted colours .Metallic butterflies fluttering and hidden in branches attract gazes .This structure is more suitable for cross roads and would offer  passers-by an invitation to come closer and warm up under it",
      "dimension (Standard)": "20'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS023_pic1.jpeg - Google Drive",
      "pic_2": "MS023_2.jpg - Google Drive",
      "pic_3 link": "MS023_3.jpg - Google Drive",
      "pic_4 link": "MS023_4.jpeg - Google Drive"
    },
     {
      "Name": "Twinkling Pole",
      "product_code": "MS024",
      "description": "This stunning sculpture can give outdoor area a face lift .The warm glow of light displays its flamboyant presence",
      "dimension (Standard)": "22'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS024_1.jpeg - Google Drive",
      "pic_2": "MS024_2.jpg - Google Drive",
      "pic_3 link": "MS024_3.jpg - Google Drive",
      "pic_4 link": "MS024_4.jpeg - Google Drive"
    },
    {
      "Name": "Jointless Round Table",
      "product_code": "MS025",
      "description": "One piece furniture adds decour to indoor as well as outdoor area.Sleek,elegant,classy and exquisite collection caters comfort to everyday users.",
      "dimension (Standard)": "48\"*27\"*18\"",
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS025.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Z Table (With Glass)",
      "product_code": "MS026",
      "description": "These coffee tables with glass frame crafted with precision would definitely generate manificence.",
      "dimension (Standard)": "48\"*27\"*20\"",
      "Weight (Kg)": 15.5,
      "color": null,
      "category": "Premium",
      "imageURL": "MS026.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Unique Coffee Table",
      "product_code": "MS027",
      "description": "These coffee tables with glass frame crafted with precision would definitely generate manificence.",
      "dimension (Standard)": "48\"*27\"*20\"",
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS027.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
    {
      "Name": "Jointles Rectangular Table",
      "product_code": "MS028",
      "description": "One piece furniture adds decour to indoor as well as outdoor area. Sleek,elegant,classy and exquisite collection caters comfort to everyday users.",
      "dimension (Standard)": "3.5' * 3.5'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS028.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Pierre Table",
      "product_code": "MS029",
      "description": "These coffee tables with glass frame crafted with precision would definitely generate manificence.",
      "dimension (Standard)": "48\"*27\"*20\"",
      "Weight (Kg)": 28,
      "color": null,
      "category": "Premium",
      "imageURL": "MS029.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
    {
      "Name": "EQUI Table",
      "product_code": "MS030",
      "description": "These coffee tables with glass frame crafted with precision would definitely generate manificence.",
      "dimension (Standard)": "48\"*27\"*20\"",
      "Weight (Kg)": 15.5,
      "color": null,
      "category": "Premium",
      "imageURL": "MS030.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Rogness Table",
      "product_code": "MS031",
      "description": "These coffee tables with glass frame crafted with precision would definitely generate manificence.",
      "dimension (Standard)": "48\"*27\"*20\"",
      "Weight (Kg)": 20,
      "color": null,
      "category": "Premium",
      "imageURL": "MS031.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Jointless Square Table",
      "product_code": "MS032",
      "description": "One piece furniture adds decour to indoor as well as outdoor area. Sleek,elegant,classy and exquisite collection caters comfort to everyday users.",
      "dimension (Standard)": null,
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS032.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Bro XAP",
      "product_code": "MS033",
      "description": "These benches suit the needs of a garden , manifest artistry as well as stylishness.",
      "dimension (Standard)": "72\" * 32\" * 18\"",
      "Weight (Kg)": 95,
      "color": null,
      "category": "Premium",
      "imageURL": "MS033.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
    {
      "Name": "Zun Garden Bench",
      "product_code": "MS034",
      "description": "These benches suit the needs of a garden , manifest artistry as well as stylishness.",
      "dimension (Standard)": "63\"*31\"*25\"",
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "garden bench.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
    {
      "Name": "Bench with flower pots",
      "product_code": "MS035",
      "description": "These benches suit the needs of a garden , manifest artistry as well as stylishness.",
      "dimension (Standard)": null,
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "pot bench.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Border Bench",
      "product_code": "MS036",
      "description": "These benches suit the needs of a garden , manifest artistry as well as stylishness.",
      "dimension (Standard)": "63\"*31\"*25\"",
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "bench.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "SS Ball",
      "product_code": "MS037",
      "description": "Mirrored sculpture made of stainless steel plates, is self imposing and projects flawless reflections around itself. It serves the purpose of a selfie point too.",
      "dimension (Standard)": "6'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Connoisseur",
      "imageURL": "MS037_1.jpeg - Google Drive",
      "pic_2": "MS037_2.jpg - Google Drive",
      "pic_3 link": null,
      "pic_4 link": null
    },
    {
      "Name": "SS Embossed Ring",
      "product_code": "MS038",
      "description": "A stainless steel sculpture which transmits,reflects and refracts everything around itself.The excellence in artistry would be surely deciphered by the spectators.",
      "dimension (Standard)": "6'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Connoisseur",
      "imageURL": "MS038.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Pot Holder",
      "product_code": "MS039",
      "description": "Cartoon miniature plant holder carved in various design to set  the mood of anyone in outdoors.Designs can be customised as per requirement.",
      "dimension (Standard)": "20\" * 26\" * 14\"",
      "Weight (Kg)": 6,
      "color": null,
      "category": "Regular",
      "imageURL": "MS039.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Butterfly Pot Holder",
      "product_code": "MS040",
      "description": "An adorable metallic creation serving purpose of holding innumerable plants in symmetry and representing a butterfly.",
      "dimension (Standard)": "17'* 10'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "mS040.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
    {
      "Name": "Cycle Symbol",
      "product_code": "MS041",
      "description": "A metallic cycle representation for magnifying cycle track.Users can customise figures as per their requirement.",
      "dimension (Standard)": null,
      "Weight (Kg)": null,
      "color": null,
      "category": "Regular",
      "imageURL": "MS041.jpeg - Google Drive",
      "pic_2": "MS041_pic2.jpeg - Google Drive",
      "pic_3 link": null,
      "pic_4 link": null
    },
    {
      "Name": "Renaissance Iron",
      "product_code": "MS042",
      "description": "A metallic sculpture imitating plants, perfect to lift ambience of outdoor area.",
      "dimension (Standard)": "8'",
      "Weight (Kg)": null,
      "color": null,
      "category": "Connoisseur",
      "imageURL": "MS042.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
    {
      "Name": "Celebrating Lifes",
      "product_code": "MS043",
      "description": "A stainless steel sculpture with intricate designs to add grandeaur to outdoor area.",
      "dimension (Standard)": "7.5' * 2'",
      "Weight (Kg)": 16,
      "color": null,
      "category": "Connoisseur",
      "imageURL": "MS043 pic1.jpeg - Google Drive",
      "pic_2": "MS043 pic2.jpeg - Google Drive",
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Metal Moon Lamp",
      "product_code": "MS044",
      "description": "Creative metallic miniature sculpture is strikingly offset by a gilt aureole.",
      "dimension (Standard)": "7' * 1'",
      "Weight (Kg)": 17,
      "color": null,
      "category": "Premium",
      "imageURL": "MS 044.jpg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
    {
      "Name": "Ironbark",
      "product_code": "MS045",
      "description": "Creative metallic miniature sculpture is strikingly offset by a gilt aureole.",
      "dimension (Standard)": null,
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS045.jpg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Balacing Ball Lamp",
      "product_code": "MS046",
      "description": "Creative metallic miniature sculpture is strikingly offset by a gilt aureole.",
      "dimension (Standard)": "68'' * 14''",
      "Weight (Kg)": 14,
      "color": null,
      "category": "Premium",
      "imageURL": "https://drive.google.com/file/d/1i7SL6tmZXPqsR7LK9wIbemwdLed4N3Td/view",
      "pic_2": "MS046 pic2.jpg - Google Drive",
      "pic_3 link": null,
      "pic_4 link": null
    },
    {
      "Name": "SS Feather Leaf",
      "product_code": "MS047",
      "description": "A stainless steel sculpture with intricate designs to add grandeaur to outdoor area.",
      "dimension (Standard)": null,
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS047.jpg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "SS Puerta",
      "product_code": "MS048",
      "description": "A stainless steel gateway to define the magnificence and splendour of a place.",
      "dimension (Standard)": null,
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS048_pic1.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Metal Arbor",
      "product_code": "MS049",
      "description": "Arbor is a great way to add a special feature to outdoor area.A boost of style while standing adorably with climbing vines and flowers generate a striking focal point.",
      "dimension (Standard)": null,
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS049 _1.jpeg - Google Drive",
      "pic_2": "MS049_2.jpeg - Google Drive",
      "pic_3 link": "MS049_3.jpeg - Google Drive",
      "pic_4 link": null
    },
     {
      "Name": "Metal Honey Nest",
      "product_code": "MS050",
      "description": "A metallic sculpture imitating a beehive, perfect to lift ambience of outdoor area.",
      "dimension (Standard)": null,
      "Weight (Kg)": null,
      "color": null,
      "category": "Connoisseur",
      "imageURL": "MS050_1.jpeg - Google Drive",
      "pic_2": "MS050_2.jpeg - Google Drive",
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Circle of Vision",
      "product_code": "MS051",
      "description": "A metallic circle with intricate design ti capture the phenomenon of nature .",
      "dimension (Standard)": null,
      "Weight (Kg)": null,
      "color": null,
      "category": "Connoisseur",
      "imageURL": "MS051.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "SS Lotus Leaf",
      "product_code": "MS052",
      "description": "A stainless steel lotus shaped sculpture with intricate designs to add grandeaur to outdoor area.",
      "dimension (Standard)": null,
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS052.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
     {
      "Name": "Curved Garden Bench",
      "product_code": "MS053",
      "description": "These benches suit the needs of a garden, manifest artistry as well as stylishness.",
      "dimension (Standard)": null,
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "brownbench.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
   {
      "Name": "Murphy Bench",
      "product_code": "MS054",
      "description": "These benches suit the needs of a garden, manifest artistry as well as stylishness.",
      "dimension (Standard)": null,
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS054.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
    {
      "Name": "Rockmetal bench",
      "product_code": "MS055",
      "description": "These benches suit the needs of a garden, manifest artistry as well as stylishness.",
      "dimension (Standard)": null,
      "Weight (Kg)": null,
      "color": null,
      "category": "Premium",
      "imageURL": "MS055.jpeg - Google Drive",
      "pic_2": null,
      "pic_3 link": null,
      "pic_4 link": null
    },
]